# Generated by Django 3.2.4 on 2021-06-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=100)),
                ('report_reporter', models.CharField(max_length=100)),
                ('report_date', models.CharField(max_length=100)),
                ('report_place', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
